- name: catalogue-playbook
  hosts: catalogue
  become: yes
  tasks:
  - name: disable existing nodejs module stream
    command: dnf module disable nodejs -y
  - name: enable nodejs:20 module stream 
    command: dnf module enable nodejs:20 -y
  - name: install nodejs
    dnf:
      name: nodejs
      state: installed
  - name: create roboshop user
    user:
      name: roboshop
      home: /app
      shell: /sbin/nologin
      system: yes
      comment: "roboshop user created"
  - name: create /app folder
    file:
      path: /app
      state: directory
      mode: '0755'
  - name: download catalogue-v3
    get_url:
      url: "https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip"
      dest: /tmp/catalogue.zip
      mode: '0644'
  - name: extract /tmp/catalogue.zip into /app
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes
  - name: update the package.json after unzip
    command: bash -c cd /app && npm install
  - name: create systemd catalogue service 
    copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service
    notify: reload-catalogue-service
  handlers:
    - name: reload-catalogue-service
      service:
        name: catalogue
        state: restarted

  
